#!/bin/bash
jupyter serverextension enable --config /srv/venv/etc/jupyter/jupyter_notebook_config.json --py scriptedforms
echo "c.NotebookApp.default_url = '/scriptedforms/detailed.md'" >> ~/.jupyter/jupyter_notebook_config.py